apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: azimuteerp-platform
#common configuration shared between all applications
data:
  application.yml: |-
    configserver:
      name: Consul
      status: Connected to Consul running in Kubernetes
    jhipster:
      security:
        authentication:
          jwt:
            base64-secret: NjY3OWEyOWQyZmQ3NTM2NTRjMmYxMDUxYzc2M2IwOWY0OWRhMDRkMGYyYmI4NTI4NWU5OTQ3ZWFjZGQ2N2EyNjBiNDk5NWM2M2Q2OTMwYmFkOTRkMTdkZTA0ZjEzN2QzYmU1NA==
  # app specific configuration
